[package]
name = "mcnotify"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
inotify = "0.11"
regex = "1.7"
reqwest = {version = "0.12.8", features = ["blocking"]}
serde = "1.0.210"
