version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:  
  publish:
    docker:
      - image: cimg/base:current
    environment:
      IMAGE_NAME: "${DOCKER_REG}/mcnotify:latest"
    steps:
      - checkout:
          path: ~/myfragshelf
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build --tag mfs_backend .
      - run:
          name: Set image tags
          command: docker tag mfs_backend:latest "${IMAGE_NAME}"
      - run:
          name: Login to docker registry
          command: echo "${DOCKER_REG_PASS}" | docker login ${DOCKER_REG} --username "${DOCKER_REG_USER}" --password-stdin 
      - run:
          name: Push docker image
          command: docker image push ${IMAGE_NAME}
      - discord/status:
          webhook: "${DISCORD_CI_URL}"
          success_message: ":green_circle: **publish-mcnotify** build from **${CIRCLE_USERNAME}** was successful."
          failure_message: ":red_circle:  **publish-mcnotify** build from **${CIRCLE_USERNAME}**' failed."

workflows:
  publish:
    jobs:
      - publish:
          context: ci-secrets
      


