version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:  
  publish:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build --tag mcnotify:latest .
      - run:
          name: Set image tags
          command: docker tag mcnotify:latest "${DOCKER_REG}/mcnotify:latest"
      - run:
          name: Login to docker registry
          command: echo "${DOCKER_REG_PASS}" | docker login ${DOCKER_REG} --username "${DOCKER_REG_USER}" --password-stdin 
      - run:
          name: Push docker image
          command: docker image push "${DOCKER_REG}/mcnotify:latest"
      - discord/status:
          webhook: "${DISCORD_CI_URL}"
          success_message: ":green_circle: **publish-mcnotify** build from **${CIRCLE_USERNAME}** was successful."
          failure_message: ":red_circle:  **publish-mcnotify** build from **${CIRCLE_USERNAME}**' failed."

workflows:
  publish:
    jobs:
      - publish:
          context: ci-secrets
      


